import '@/styles/style.scss';
import '@/js/v-menu.js';
import '@/js/menu.js';
// import '@/js/sub-menu.js';
import '@/js/callMaster.js';
import '@/js/header.js';
import '@/js/specialists-slider.js';
import '@/js/visit-form.js';
import '@/js/service-works.js';
import '@/js/works-and_reviews.js';
import '@/js/windows-calc.js';
import '@/js/grids-calc.js';
import '@/js/calc.js';
import '@/js/video.js';
import '@/js/percentForm.js';
